# -*- coding: utf-8 -*-
"""calc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GY_Q9qA_zBSbyEihw8sHuqQ7ALo7kpDU
"""

import math
ti=float(input())
print(ti)
Vo=float(input())
print(Vo)
t=float(input())
print(t)
v=float(input())
t-=ti
print(t)
print(math.log((5-Vo)/(5-v)))
print(t/math.log((5-Vo)/(5-v)))

print(t/(math.log((5-Vo)/(5-v))))